package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema      string `json:"api_schema"`
	MaterialCode   string `json:"material_code"`
	Plant_Supplier string `json:"plant/supplier"`
	Stock          string `json:"stock"`
	DocumentType   string `json:"document_type"`
	DocumentNo     string `json:"document_no"`
	PlannedDate    string `json:"planned_date"`
	ValidatedDate  string `json:"validated_date"`
	Deleted        bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey        string `json:"connection_key"`
	Result               bool   `json:"result"`
	RedisKey             string `json:"redis_key"`
	Filepath             string `json:"filepath"`
	CompetitorCollection struct {
		ObjectID                          string `json:"ObjectID"`
		CompetitorID                      string `json:"CompetitorID"`
		CompetitorUUID                    string `json:"CompetitorUUID"`
		StatusCode                        string `json:"StatusCode"`
		StatusCodeText                    string `json:"StatusCodeText"`
		ClassificationCode                string `json:"ClassificationCode"`
		ClassificationCodeText            string `json:"ClassificationCodeText"`
		BusinessPartnerFormattedName      string `json:"BusinessPartnerFormattedName"`
		Name                              string `json:"Name"`
		AdditionalName                    string `json:"AdditionalName"`
		FormattedPostalAddressDescription string `json:"FormattedPostalAddressDescription"`
		CountryCode                       string `json:"CountryCode"`
		CountryCodeText                   string `json:"CountryCodeText"`
		RegionCode                        string `json:"RegionCode"`
		RegionCodeText                    string `json:"RegionCodeText"`
		CareOfName                        string `json:"CareOfName"`
		AddressLine1                      string `json:"AddressLine1"`
		AddressLine2                      string `json:"AddressLine2"`
		HouseNumber                       string `json:"HouseNumber"`
		Street                            string `json:"Street"`
		AddressLine4                      string `json:"AddressLine4"`
		AddressLine5                      string `json:"AddressLine5"`
		City                              string `json:"City"`
		AdditionalCityName                string `json:"AdditionalCityName"`
		District                          string `json:"District"`
		County                            string `json:"County"`
		CompanyPostalCode                 string `json:"CompanyPostalCode"`
		StreetPostalCode                  string `json:"StreetPostalCode"`
		POBoxPostalCode                   string `json:"POBoxPostalCode"`
		POBox                             string `json:"POBox"`
		POBoxDeviatingCountryCode         string `json:"POBoxDeviatingCountryCode"`
		POBoxDeviatingCountryCodeText     string `json:"POBoxDeviatingCountryCodeText"`
		POBoxDeviatingCity                string `json:"POBoxDeviatingCity"`
		TimeZoneCode                      string `json:"TimeZoneCode"`
		TimeZoneCodeText                  string `json:"TimeZoneCodeText"`
		TaxJurisdictionCode               string `json:"TaxJurisdictionCode"`
		TaxJurisdictionCodeText           string `json:"TaxJurisdictionCodeText"`
		POBoxDeviatingStateCode           string `json:"POBoxDeviatingStateCode"`
		POBoxDeviatingStateCodeText       string `json:"POBoxDeviatingStateCodeText"`
		Phone                             string `json:"Phone"`
		Fax                               string `json:"Fax"`
		Email                             string `json:"Email"`
		WebSite                           string `json:"WebSite"`
		LanguageCode                      string `json:"LanguageCode"`
		LanguageCodeText                  string `json:"LanguageCodeText"`
		BestReachedByCode                 string `json:"BestReachedByCode"`
		BestReachedByCodeText             string `json:"BestReachedByCodeText"`
		NormalisedPhone                   string `json:"NormalisedPhone"`
		CreatedOn                         string `json:"CreatedOn"`
		CreatedBy                         string `json:"CreatedBy"`
		CreatedByIdentityUUID             string `json:"CreatedByIdentityUUID"`
		ChangedOn                         string `json:"ChangedOn"`
		ChangedBy                         string `json:"ChangedBy"`
		ChangedByIdentityUUID             string `json:"ChangedByIdentityUUID"`
		EntityLastChangedOn               string `json:"EntityLastChangedOn"`
		ETag                              string `json:"ETag"`
	} `json:"CompetitorCollection"`
	APISchema      string   `json:"api_schema"`
	Accepter       []string `json:"accepter"`
	CompetitorCode string   `json:"competitor_code"`
	Deleted        bool     `json:"deleted"`
}
